#!/usr/bin/env bash
# Write Bash (init) script 11-manage_my_process that manages manage_my_process
case "$1" in
  start)
    nohup ./manage_my_process > /dev/null 2>&1 &

    touch /var/run/my_process.pid
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)

    kill $(cat /var/run/my_process.pid)

    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)

    kill $(cat /var/run/my_process.pid)

    rm /var/run/my_process.pid

    nohup ./manage_my_process > /dev/null 2>&1 &

    touch /var/run/my_process.pid
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
