#!/usr/bin/env bash
# Write Bash (init) script 11-manage_my_process that manages manage_my_process

PID_FILE="/var/run/my_process.pid"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already started."
    else
        nohup ./manage_my_process  >/dev/null 2>&1 &
        echo $! > "$PID_FILE"
        echo "manage_my_process started."
    fi
}

stop() {
    if [ -f i"$PID_FILE" ]; then
        kill "$(cat "$PID_FILE")"
        rm "$PID_FILE"
        echo "manage_my_process stopped."
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac

